La crisis de la deuda externa de 1982 implicó que la estabilización monetaria y de precios se convirtiera en un objetivo prioritario de la política económica en México. El gobierno mexicano adoptó diferentes modelos de metas de inflación con el objetivo de estabilizar los fundamentos macroeconómicos. (Fortuno y Perrotini). En 1994-1995, se adoptó un nuevo marco de política monetaria que establece una meta de inflación que depende de ajustes en la tasa de interés. En 2001, el Banco de México adoptó regla de Taylor para la estimación de la tasa de interés a corto plazo. A partir del 21 de enero de 2008, el Banco de México adoptó como objetivo operacional la tasa de interés interbancaria a un día (“tasa de fondeo bancario”) en sustitución del saldo sobre las cuentas corrientes que la banca mantiene en el propio Banco (objetivo conocido como el “corto”).
En 1993, John B. Taylor diseñó una regla de política monetaria que permitiera a las autoridades monetarias afianzar la producción real alrededor de una meta y a controlar la inflación. La regla de política sustituye a la curva LM, por lo que, los bancos centrales se centrarán en estabilizar la tasa de interés a muy corto plazo, considerando el valor de la tasa de interés neutral, la tasa de inflación y la intención de igualar la producción real con el potencial.
La política monetaria influye en la demanda agregada y la inflación con el objetivo de estabilizar la economía alrededor de su tendencia. Los bancos centrales emplean la tasa de interés a corto plazo como mecanismo que afecta las decisiones de gasto, ahorro e inversión de los agentes económicos. Un cambio en la tasa de interés nominal influye en las tasas de interés reales. En consecuencia, el aumento de la tasa de interés reduce la oferta de crédito bancario mediante el mecanismo de selección adversa. 
Los bancos centrales determinan sus decisiones de forma discrecionales, sin embargo, es posible identificar ciertas conductas regulares que se pueden modelos a partir de reglas para la evaluación de las variables que determinan las decisiones monetarias. Por lo tanto, el empleo de reglas o móndelos que describan el comportamiento de los bancos centrales para proyectar la trayectoria de la política monetaria.  (Galindo y Lizardi).
La regla establece que cuando el producto real y la tasa de inflación exceden los objetivos, la tasa de interés nominal incrementa para influir directamente en la tasa de interés real con el fin de reducir la demanda agregada. Por el contrario, si la inflación y el nivel de producción real caen por debajo de las metas se recomienda disminuir la tasa de interés nominal para incentivar la demanda agregada por el mecanismo de un aumento de la tasa de interés real. 
Por tal razón, la tasa de interés es el principal mecanismo de estabilización de la economía en el corto plazo con el propósito de que el sistema de precios emita señales a los agentes para la asignación y una distribución eficiente de los recursos físico y humanos que promueva el crecimiento sostenido. 


In [1]:
import numpy as np
import pandas as pd

In [2]:
RT = pd.read_csv('RegladeTaylor.csv')
RT.head()

FECHA     Y    X1       X2        X3        X4
0  2009q1  7.72  0.20  14.6066  3.177613 -2.537608
1  2009q2  5.27  0.17  13.3414  2.978988 -1.967703
2  2009q3  4.51  0.15  13.3623  2.081610 -0.507883
3  2009q4  4.54  0.12  13.1115  0.861444  1.985399
4  2010q1  4.57  0.13  12.8096  1.819982 -1.953984

In [3]:
RT.set_index('FECHA', inplace = True)
RT.head()

Y    X1       X2        X3        X4
FECHA                                          
2009q1  7.72  0.20  14.6066  3.177613 -2.537608
2009q2  5.27  0.17  13.3414  2.978988 -1.967703
2009q3  4.51  0.15  13.3623  2.081610 -0.507883
2009q4  4.54  0.12  13.1115  0.861444  1.985399
2010q1  4.57  0.13  12.8096  1.819982 -1.953984

In [4]:
# Generar el vector (variable) X1 al dataframe
RT['X0']=1
RT.head()

Y    X1       X2        X3        X4  X0
FECHA                                              
2009q1  7.72  0.20  14.6066  3.177613 -2.537608   1
2009q2  5.27  0.17  13.3414  2.978988 -1.967703   1
2009q3  4.51  0.15  13.3623  2.081610 -0.507883   1
2009q4  4.54  0.12  13.1115  0.861444  1.985399   1
2010q1  4.57  0.13  12.8096  1.819982 -1.953984   1

In [6]:
# Transformar el dataframe a matrices mediante "numpy"
y = RT['Y'].to_numpy()
display(y)

array([ 7.72 ,  5.27 ,  4.51 ,  4.54 ,  4.57 ,  4.59 ,  4.6  ,  4.55 ,
        4.53 ,  4.5  ,  4.45 ,  4.41 ,  4.5  ,  4.5  ,  4.49 ,  4.5  ,
        4.49 ,  4.02 ,  4.01 ,  3.61 ,  3.51 ,  3.53 ,  3.03 ,  3.05 ,
        3.06 ,  3.045,  3.07 ,  3.06 ,  3.36 ,  3.79 ,  4.28 ,  4.905,
        6.22 ,  6.72 ,  7.03 ,  7.03 ,  7.51 ,  7.55 ,  7.79 ,  7.935,
        8.25 ,  8.28 ,  8.26 ,  7.75 ,  7.13 ,  5.715,  4.63 ,  4.25 ,
        4.09 ,  4.02 ,  4.47 ,  4.94 ,  5.95 ,  6.91 ,  8.47 ,  9.98 ,
       10.97 ])

In [7]:
X =RT[['X0', 'X1', 'X2', 'X3', 'X4']].to_numpy()
display(X)

array([[ 1.00000000e+00,  2.00000000e-01,  1.46066000e+01,
         3.17761258e+00, -2.53760790e+00],
       [ 1.00000000e+00,  1.70000000e-01,  1.33414000e+01,
         2.97898796e+00, -1.96770310e+00],
       [ 1.00000000e+00,  1.50000000e-01,  1.33623000e+01,
         2.08160961e+00, -5.07882770e-01],
       [ 1.00000000e+00,  1.20000000e-01,  1.31115000e+01,
         8.61444302e-01,  1.98539870e+00],
       [ 1.00000000e+00,  1.30000000e-01,  1.28096000e+01,
         1.81998214e+00, -1.95398440e+00],
       [ 1.00000000e+00,  2.00000000e-01,  1.27102000e+01,
         9.15885019e-01,  1.21076630e+00],
       [ 1.00000000e+00,  1.90000000e-01,  1.27977000e+01,
         6.55567839e-01,  4.11202640e-01],
       [ 1.00000000e+00,  1.90000000e-01,  1.23902000e+01,
         1.28086078e+00,  1.88378740e+00],
       [ 1.00000000e+00,  1.50000000e-01,  1.20649000e+01,
         5.60520399e-01, -1.83342480e+00],
       [ 1.00000000e+00,  9.00000000e-02,  1.17059000e+01,
         2.51155316e-01

In [8]:
np.set_printoptions(suppress = True)
display(X)

array([[  1.        ,   0.2       ,  14.6066    ,   3.17761258,
         -2.5376079 ],
       [  1.        ,   0.17      ,  13.3414    ,   2.97898796,
         -1.9677031 ],
       [  1.        ,   0.15      ,  13.3623    ,   2.08160961,
         -0.50788277],
       [  1.        ,   0.12      ,  13.1115    ,   0.8614443 ,
          1.9853987 ],
       [  1.        ,   0.13      ,  12.8096    ,   1.81998214,
         -1.9539844 ],
       [  1.        ,   0.2       ,  12.7102    ,   0.91588502,
          1.2107663 ],
       [  1.        ,   0.19      ,  12.7977    ,   0.65556784,
          0.41120264],
       [  1.        ,   0.19      ,  12.3902    ,   1.28086078,
          1.8837874 ],
       [  1.        ,   0.15      ,  12.0649    ,   0.5605204 ,
         -1.8334248 ],
       [  1.        ,   0.09      ,  11.7059    ,   0.25115532,
          0.22723345],
       [  1.        ,   0.08      ,  12.2366    ,   0.42410037,
          0.71399361],
       [  1.        ,   0.07      ,  13.695

In [9]:
# Transponer a la matrix X
trX = X.T
print(trX)

[[  1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.           1.           1.           1.
    1.           1.        ]
 [  0.2          0.17         0.15         0.12         0.13
    0.2          0.19         0.19         0.15         0.09
    0.08         0.07         0.11         0.16         0.14
    0.16         0.14         0.12         0.09         0.09
    0.07         0.09         0.09         0.09         0.12
    0.13         

In [10]:
# Obtener (X'X)
X_X = np.dot(trX, X)
display(X_X)

array([[   57.        ,    38.48      ,   944.8821    ,    84.19193917,
           -4.44454133],
       [   38.48      ,    81.03855   ,   720.0131265 ,    94.61720042,
           62.08485547],
       [  944.8821    ,   720.0131265 , 16306.25458273,  1481.51628955,
         -164.47621794],
       [   84.19193917,    94.61720042,  1481.51628955,   256.83293129,
           38.92383691],
       [   -4.44454133,    62.08485547,  -164.47621794,    38.92383691,
          588.85452294]])

In [11]:
# determinante de (X'X)
print(np.linalg.det(X_X))

75818803831.36862


In [12]:
# inversa de X_X
invX_X = np.linalg.inv(X_X)
display(invX_X)

array([[ 0.54224764,  0.05079351, -0.03376469, -0.0000773 , -0.01068846],
       [ 0.05079351,  0.03207365, -0.00391332, -0.00532617, -0.00373924],
       [-0.03376469, -0.00391332,  0.0022564 , -0.00063158,  0.00082974],
       [-0.0000773 , -0.00532617, -0.00063158,  0.0095618 , -0.00024748],
       [-0.01068846, -0.00373924,  0.00082974, -0.00024748,  0.0022599 ]])

In [13]:
# Obtener X'y
Xy = np.dot(trX, y)
display(Xy)

array([ 305.9       ,  301.49315   , 5252.627625  ,  547.65401658,
         61.72010885])

In [14]:
# Obtener al vector beta
beta = np.dot(invX_X, Xy)
print(beta)

[ 3.13210268  1.5048419   0.048905    0.27437573 -0.03468271]


In [15]:
print('y=  3.13210268 + 1.5048419X2+ 0.048905X3+ 0.27437573X4- -0.03468271X5')

y=  3.13210268 + 1.5048419X2+ 0.048905X3+ 0.27437573X4- -0.03468271X5


In [16]:
# Obtener SRC = u'u = y'y - B'X'y
Try = y.T
y_y = np.dot(Try,y)
display(y_y)

1846.9763

In [17]:
# Transponer a beta
TrB = beta.T
display(TrB)

array([ 3.13210268,  1.5048419 ,  0.048905  ,  0.27437573, -0.03468271])

In [18]:
BXy = np.dot(TrB,Xy)
display(BXy)

1816.8118295416707

In [19]:
u_u = y_y - BXy
display(u_u)

30.164470458329333

In [20]:
# var(u) = u'u / n-k
RT.describe()

Y         X1         X2         X3         X4    X0
count  57.000000  57.000000  57.000000  57.000000  57.000000  57.0
mean    5.366667   0.675088  16.576879   1.477052  -0.077974   1.0
std     1.914759   0.991582   3.388685   1.538071   3.241770   0.0
min     3.030000   0.050000  11.705900  -0.737788 -18.437189   1.0
25%     4.090000   0.090000  13.111500   0.424100  -0.978920   1.0
50%     4.540000   0.150000  17.808100   1.024114   0.271585   1.0
75%     7.030000   0.910000  19.552500   2.081610   1.552757   1.0
max    10.970000   4.575000  23.524000   5.631372   4.500170   1.0

In [22]:
n_k = 57-5
print(n_k)

52


In [23]:
var_u = u_u / n_k
print(var_u)

0.5800859703524872


In [24]:
sd_var_u = var_u**(1/2)
print(sd_var_u)

0.7616337507965933


In [25]:
# Obtener la matriz var_cov(beta) = var(u)*inv(x'x)
var_cov_beta = var_u*invX_X
display(var_cov_beta)

array([[ 0.31455025,  0.02946461, -0.01958642, -0.00004484, -0.00620022],
       [ 0.02946461,  0.01860548, -0.00227006, -0.00308963, -0.00216908],
       [-0.01958642, -0.00227006,  0.00130891, -0.00036637,  0.00048132],
       [-0.00004484, -0.00308963, -0.00036637,  0.00554667, -0.00014356],
       [-0.00620022, -0.00216908,  0.00048132, -0.00014356,  0.00131093]])

In [26]:
ee_B0 = 0.30861534**0.5
ee_B1 = 0.01825443**0.5
ee_B2 = 0.00128421**0.5
ee_B3 = 0.00544201**0.5
ee_B4 = 0.0012862**0.5
print(ee_B0, ee_B1, ee_B2, ee_B3, ee_B4)

0.555531583260574 0.13510895603178938 0.0358358758787894 0.07376998034431079 0.03586363060260352


In [28]:
# Obtener el coeficiente de determinación R^2 
# R^2 = (B'X'y - n*medY^2)/(y'y - n*medY^2)
medY2 = RT['Y'].mean()**2
medY2

28.801111111111116

In [29]:
R2 = (BXy - (57*medY2)) / (y_y - 57*medY2)
R2

0.8530805387109206

In [30]:
# Se procede a estimar al modelo de manera directa
print(RT.shape)

(57, 6)


In [32]:
import statsmodels.api as sm
from statsmodels.iolib.summary2 import summary_col

In [33]:
#Estimar el modelo
mod1 = sm.OLS(endog = RT['Y'],
             exog = RT[['X0','X1','X2','X3','X4']])

In [34]:
# Obtener los resultados del modelo
est_mod1 = mod1.fit()

In [35]:
# presentar los resultados
print(est_mod1.summary())

                            OLS Regression Results                            
Dep. Variable:                      Y   R-squared:                       0.853
Model:                            OLS   Adj. R-squared:                  0.842
Method:                 Least Squares   F-statistic:                     75.48
Date:                Tue, 28 Nov 2023   Prob (F-statistic):           5.12e-21
Time:                        17:58:22   Log-Likelihood:                -62.742
No. Observations:                  57   AIC:                             135.5
Df Residuals:                      52   BIC:                             145.7
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X0             3.1321      0.561      5.585      0.0

In [36]:
# Matrix de correlación
corr_RT = RT.corr()
corr_RT

Y        X1        X2        X3        X4  X0
Y   1.000000  0.893344  0.500225  0.581026  0.246178 NaN
X1  0.893344  1.000000  0.436495  0.442356  0.361563 NaN
X2  0.500225  0.436495  1.000000  0.294225 -0.147599 NaN
X3  0.581026  0.442356  0.294225  1.000000  0.162913 NaN
X4  0.246178  0.361563 -0.147599  0.162913  1.000000 NaN
X0       NaN       NaN       NaN       NaN       NaN NaN